### ISSUE TITLE
React Native compatibility

### ISSUE THREAD

**Issue by tsyirvo** [unsplash/react-trend#14]
Hey,

I wanted to include this component in one of my React Native app but I can't manage to get it working 😔
I get the following error `Expected a component class, got [object Object]`

I used the code from the demo to be sure I wasn't using a bad prop or something.

Is this component not compatible with RN or am I doing something wrong ?

Thanks,

EDIT: I think it's because of the use of SVGs in the component. I'll check on how to use them on RN.

**Comment by joshwcomeau** [comment]
Hey there,

Sorry for the delay. Yeah, React Trend isn't compatible with RN. If anyone wants to make a RN-compatible one that'd be great and I would link to it from the README :)
