### ISSUE TITLE
How to set the background fill along with the stroke?

### ISSUE THREAD

**Issue by sivadass** [unsplash/react-trend#17]
Hi bro, first of all thanks for making such an awesome graph component!

How can I give background fill color to the svg along with the stroke. I want to achieve something like this below:

![react-trend](https://user-images.githubusercontent.com/10391786/27258866-402e12a6-5423-11e7-89d4-a3da37688dc1.PNG)

Any advice to proceed further?

**Comment by joshwcomeau** [comment]
Yikes, sorry for the delay! I thought I answered this.

Yeah, so if you're satisfied by how it looks in that example, by just adding a `fill` to the SVG path, I'd fork this project and add it (just delegate the prop down, should be very simple).

There are a few reasons it isn't officially supported:
- Depending on your line-end, the fill doesn't extend all the way. This is visible in your screenshot, and it gets worse the larger the stroke thickness is.
- `autodraw` is an animation on-mount that draws the stroke. No idea how the `fill` fits in with that.
- Ideally, `fill` would match the gradient for the line provided. 

Adding this feature the way I'd want it to be added would be a huge amount of work, and it feels funny to me to expose the `fill` in a way that is so problematic with the existing props.

**Comment by edufschmidt** [comment]
Any chance this could be implemented as in [https://danielpataki.com/svg-chart)](https://danielpataki.com/svg-chart)/ ?
