### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by ayozebarrera** [unsplash/react-trend#18]
Hi, first at all, nice job! I'm following this project months ago and I love it

I'm going to use it but first I need to know one thing

I was wondering if there is any way to show each point on the chart...

thank you!

**Comment by joshwcomeau** [comment]
Hey there! Sorry for the delay.

Yeah, so the decision was made early on that this would _only_ be for showing trends. Individual points on the line aren't supported.

Totally agree that it would be a nice addition, but it's an entirely different use-case. Unsplash would have to develop and maintain that feature, and it's not something they actively need.

**Comment by ayozebarrera** [comment]
Hey, its okay!

Good job anyway and thanks for your time!
If I develop it, you'll know ;)

:vulcan_salute:
