### ISSUE TITLE
Add Typescript typings

### ISSUE THREAD

**Issue by panmona** [unsplash/react-trend#21]
#### Technical Notes

- Have you ever thought about adding Typescript typings to your project? I would really appreciate it.

**Comment by joshwcomeau** [comment]
Sorry for the delay on this!

This project isn't really under active development, and so it's unlikely that we'd be able to add Typescript bindings. For myself, I've never used TS, but maybe @samijaber or @OliverJAsh are up for it, or for reviewing the PRs if you or someone else wants to contribute?

**Comment by dugagjin** [comment]
If someone needs the typings (put inside e.g. react-trends.d.ts):

```typescript
declare module 'react-trend' {
    interface Props {
        autoDraw?: boolean;
        autoDrawDuration?: number;
        autoDrawEasing?: string;
        data: number[] | Array<{ value: number }>;
        gradient?: string[];
        height?: number;
        padding?: number;
        radius?: number;
        smooth?: boolean;
        stroke?: string;
        strokeDasharray?: number[];
        strokeDashoffset?: number;
        strokeLinecap?: 'butt' | 'square' | 'round';
        strokeLinejoin?: string;
        strokeOpacity?: number;
        strokeWidth?: number;
        width?: number;
    }
    export default class Trend extends React.Component<Props> {}
}
```

**Comment by joshwcomeau** [comment]
Closing in anticipation of archiving the repo. Sorry for the delay on this!
