### ISSUE TITLE
Dot on the graph

### ISSUE THREAD

**Issue by 6e656d6d61** [unsplash/react-trend#23]
Is it possible to draw a small dot on the graph to show a particular value ?

**Comment by joshwcomeau** [comment]
Afraid not! This project is really just meant to give a sense of trends, not to provide explicit values. You're probably better off using something like [Victory](https://formidable.com/open-source/victory/) or D3.

You could also fork this and try to add it yourself; the source code for this project is pretty tiny and (hopefully) pretty clear, so it should be doable (although it gets more complicated if you want to maintain support for auto-draw and smoothing)
