### ISSUE TITLE
React dependency warning?

### ISSUE THREAD

**Issue by danqing** [unsplash/react-trend#24]
#### Steps to Reproduce

Add `"react-trend": "^1.2.4"` to `package.json` and `npm i`

#### Observed Behaviour

```
npm WARN react-trend@1.2.4 requires a peer of react@ but none is installed. You must install peer dependencies yourself.
```

#### Expected Behaviour

I have React installed already (16.4.2). I even tried `npm i react` again. Maybe it's due to the `@`? i.e. no version specified in the `peerDependencies` section.

**Comment by joshwcomeau** [comment]
Sorry for the huge delay, @danqing. As is probably clear by now, this project hasn't been actively maintained in a while.

Archiving this repo now, highly recommend forking the repo and owning your copy :)
