### ISSUE TITLE
Getting an error while using React Trend with React Starter Kit

### ISSUE THREAD

**Issue by mmalu** [unsplash/react-trend#25]
#### Steps to Reproduce
`  <View>
    <Trend
      smooth
      autoDraw
      autoDrawDuration={3000}
      autoDrawEasing="ease-out"
      data={[0,2,5,9,5,10,3,5,0,0,1,8,2,9,0]}
      gradient={['#f72047', '#ffd200', '#1feaea']}
      radius={10}
      strokeWidth={2}
      strokeLinecap={'butt'}
    />
  </View>`
-

#### Observed Behaviour
Error
`Invariant Violation: Invariant Violation: View config not found for name stop. Make sure to start component names with a capital letter.

This error is located at:
in stop (created by Trend)
in linearGradient (created by Trend)
in defs (created by Trend)
in svg (created by Trend)
in Trend (at ComponentsScreen.js:230)
in RCTView (at View.js:44)
in RCTScrollContentView (at ScrollView.js:852)
in RCTScrollView (at ScrollView.js:977)
in ScrollView (at ComponentsScreen.js:33)
in ComponentsScreen (created by withState(ComponentsScreen))
in withState(ComponentsScreen) (created by Connect(withState(ComponentsScreen)))
in Connect(withState(ComponentsScreen)) (created by SceneView)
in SceneView (at createTabNavigator.js:39)
in RCTView (at View.js:44)
in RCTView (at View.js:44)
in ResourceSavingScene (at createBottomTabNavigator.js:113)
in RCTView (at View.js:44)
in ScreenContainer (at createBottomTabNavigator.js:103)
in RCTView (at View.js:44)
in TabNavigationView (at createTabNavigator.js:197)
in NavigationView (created by Navigator)
in Navigator (created by SceneView)
in SceneView (at StackViewLayout.js:793)
in RCTView (at View.js:44)
in AnimatedComponent (at StackViewCard.js:69)
in RCTView (at View.js:44)
in AnimatedComponent (at screens.native.js:59)
in Screen (at StackViewCard.js:57)
in Card (at createPointerEventsContainer.js:27)
in Container (at StackViewLayout.js:858)
in RCTView (at View.js:44)
in ScreenContainer (at StackViewLayout.js:311)
in RCTView (at View.js:44)
in AnimatedComponent (at StackViewLayout.js:307)
in Handler (at StackViewLayout.js:300)
in StackViewLayout (at withOrientation.js:30)
in withOrientation (at StackView.js:79)
in RCTView (at View.js:44)
in Transitioner (at StackView.js:22)
in StackView (created by Navigator)
in Navigator (at createKeyboardAwareNavigator.js:12)
in KeyboardAwareNavigator (at createAppContainer.js:388)
in NavigationContainer (at Navigation.js:10)
in NavigatorView (created by Connect(NavigatorView))
in Connect(NavigatorView) (at App.js:59)
in RCTView (at View.js:44)
in Provider (at App.js:56)
in App (at withExpoRoot.js:22)
in RootErrorBoundary (at withExpoRoot.js:21)
in ExpoRootComponent (at renderApplication.js:34)
in RCTView (at View.js:44)
in RCTView (at View.js:44)
in AppContainer (at renderApplication.js:33)

This error is located at:
in NavigationContainer (at Navigation.js:10)
in NavigatorView (created by Connect(NavigatorView))
in Connect(NavigatorView) (at App.js:59)
in RCTView (at View.js:44)
in Provider (at App.js:56)
in App (at withExpoRoot.js:22)
in RootErrorBoundary (at withExpoRoot.js:21)
in ExpoRootComponent (at renderApplication.js:34)
in RCTView (at View.js:44)
in RCTView (at View.js:44)
in AppContainer (at renderApplication.js:33)

node_modules/react-native/Libraries/Renderer/shims/ReactNativeViewConfigRegistry.js:95:8 in get
node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:3954:53 in createInstance
... 17 more stack frames from framework internals`
-

> _Image or video please._

#### Expected Behaviour

-

#### Technical Notes

-

**Comment by mmalu** [comment]
I'm trying to use the React Trend component with https://github.com/flatlogic/react-native-starter. However, I get the error mentioned above.

**Comment by samijaber** [comment]
React Trend doesn't work with React Native: see https://github.com/unsplash/react-trend/issues/14
