### ISSUE TITLE
unsplash link not working

### ISSUE THREAD

**Issue by brandly** [unsplash/react-trend#5]
#### Steps to Reproduce

- click the link

#### Observed Behaviour

- the link times out

> _Image or video please._

#### Expected Behaviour

https://www.unsplash.com/ should redirect to https://unsplash.com/ seemingly, or in the short term, link directly to https://unsplash.com/

#### Technical Notes

-

**Comment by joshwcomeau** [comment]
Thanks for catching this, @brandly! I swear this was working a couple weeks ago.

We're gonna look into why the `www` hostname doesn't redirect, but I deployed a link update as a band-aid fix.

**Comment by brandly** [comment]
thanks @joshwcomeau! glad i could help :D
