### ISSUE TITLE
Gradient props overwritten

### ISSUE THREAD

**Issue by lndgalante** [unsplash/react-trend#6]
#### Steps to Reproduce
When I have 2 Trend components the last one will overwrite the props `gradient` from the first one.

```javascript
import React, { Component } from 'react';
import Trend from 'react-trend';

import './App.css';

export default class App extends Component {
  render() {
    return (
      <div className="container">
        <Trend
          smooth
          autoDraw
          autoDrawDuration={3000}
          autoDrawEasing="ease-out"
          data={[0, 2, 5, 9, 5, 10, 3, 5, 0, 0, 1, 8, 2, 9, 0]}
          gradient={['#DD0031', '#C3002F']}
          radius={10}
          strokeWidth={2.3}
          strokeLinecap={'round'}
          className="pos-absolute"
        />
        <Trend
          smooth
          autoDraw
          autoDrawDuration={3000}
          autoDrawEasing="ease-out"
          data={[2, 4, 10, 3, 1, 4, 9, 2, 3, 1, 6, 5, 5, 2, 7]}
          gradient={['#42b3f4']}
          radius={10}
          strokeWidth={2.3}
          strokeLinecap={'round'}
          className="pos-absolute"
        />
      </div>
    );
  }
}
```

#### Observed Behaviour
<img width="998" alt="screen shot 2017-03-08 at 12 35 24 am" src="https://cloud.githubusercontent.com/assets/2475912/23689105/36f22682-0397-11e7-8562-2da52a12d804.png">

#### Expected Behaviour

Each component should have it's own `gradient` colors.

#### Technical Notes
Using: 
* React: 15.4.2
* React-trend: 1.2.0

**Comment by joshwcomeau** [comment]
hi @Fenwil,

Sorry about that, and thanks for letting us know!

The fix is thankfully pretty straightforward. We should have a patch version released today that addresses this bug.
