### ISSUE TITLE
Errors when trend is flat

### ISSUE THREAD

**Issue by Mattasher** [unsplash/react-trend#9]
#### Steps to Reproduce

Put in data that is all the same

#### Observed Behaviour

`Error: <path> attribute d: Expected number`

#### Expected Behaviour

A flat line

#### Technical Notes

Can you please set the trend line to be flat (with no errors) if all values are the same or if there is a single value. Ideally you could set whether this should appear at the top, bottom, or middle of the graph.

**Comment by joshwcomeau** [comment]
hey @Mattasher,

Thanks for pointing this out! Hadn't run into this bug yet.

So, I don't really like the idea of adding another prop that's so specific to this problem. One thing I've been thinking about, though, is to provide `min` and `max` props.

Sometimes, for example, you have several trends side-by-side, and you want them to all share the same data scale.

It would also solve this problem; If your data was `[5, 5, 5, 5, 5]`, and you provided a `min` of 0 and a `max` of 10, your data would be a flat line along the middle. If the data was `[0, 0, 0, 0, 0]`, it would run along the bottom.

(of course, a potential problem with that approach is if you provide data outside the supplied range... but maybe I can just clamp it to the range provided, and add a console warning).

**Comment by joshwcomeau** [comment]
Published a basic fix, where lines will run along the baseline when all values are the same.

In the future, a minor version bump will allow the `min`/`max` props I described above (or something similar).

**Comment by Mattasher** [comment]
Excellent! Thanks. If you want to see it in action I've added trendlines to [http://growhive.io/](http://growhive.io/) in the upper left corner you'll have to leave "The Nursery" and go to other Sectors to accumulate Score & Nectar.

**Comment by joshwcomeau** [comment]
@Mattasher this is awesome!! Thanks so much for sharing, love seeing where things get used :)

I do see the issue, where once the trend fills up with the same value (eg. my score of 3 has been static the whole while), the line jumps back down to baseline. Min/max will fix that, hopefully I can make some time for it soon.

**Comment by joshwcomeau** [comment]
(sadly, min/max is not something we need at Unsplash yet, so it's hard to justify the time for it - if you'd like to work on it, though, I'd gladly accept PRs!)
